###read all users
GET http://localhost:3000/user-api/users

### read user by id
GET http://localhost:3000/user-api/users/5

### create new user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":5,
    "name":"shiva",
    "age":20
}



### update a user
PUT http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":5,
    "name":"bhanu",
    "age":22
}
 

### delete a user by id
DELETE http://localhost:3000/user-api/users/5



###create new product
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId": 1,
    "name": "Laptop",
    "brand": "Dell",
    "price": 50000
}

###read all products
GET http://localhost:3000/product-api/products


###read product by brand
GET http://localhost:3000/product-api/products/brand/Dell

###update a product
PUT http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId": 1,
    "name": "Laptop",
    "brand": "Dell",
    "price": 55000
}


###delete a product
DELETE http://localhost:3000/product-api/products/1